backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use InvalidArgumentException;
use backend\models\LoginForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'login', 'error', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //return $this->render('index');
        return $this->redirect(['user/index']);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Запрос смены пароля.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success',
                    'Письмо с инструкциями по смене пароля было отправлено Вам на электронную почту.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Письмо с ссылкой для смены пароля не было отправлено.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Смена пароля.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     * @throws \yii\base\Exception
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль сохранен.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

use common\models\Genres;
use common\models\Visitors;
use common\models\GenresHistory;
use yii\web\Response;


/**
 * Site controller
 */
class SiteController extends Controller
{

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	/**
	 * Index page
	 *
	 * @return mixed
	 * @throws NotFoundHttpException
	 */
	public function actionIndex()
	{

		$dataProvider = new ActiveDataProvider([
			'query' => Visitors::find(),
		]);

		return $this->render('index', [
			'dataProvider' => $dataProvider,
			'currentMusic' => $this->getCurrentMusic(),
			'exitsVisitors' => $this->checkExistVisitors(),
		]);
	}

	/**
	 * Change current music
	 * The browser will be redirected to the 'index' page.
	 *
	 * @return Response
	 * @throws NotFoundHttpException
	 * @throws \Throwable
	 */
	public function actionChangeMusic()
	{

		$lastGenre = $this->getLastMusic();
		$lastPlayMusic = $lastGenre->genre->genre_id;

		$variants = Genres::find()->select(['genre_id'])->where(['!=', 'genre_id', $lastPlayMusic])->asArray()->all();

		$newGenreHistory = new GenresHistory();
		$newGenreHistory->genre_id = $variants[array_rand($variants)]['genre_id'];
		$newGenreHistory->save();

		$this->changeStatus();

		return $this->redirect(['index']);
	}

	/**
	 * Check the status bar
	 * The browser will be redirected to the 'index' page.
	 *
	 * @return Response
	 * @throws \Throwable
	 */
	public function actionCheckBarStatus()
	{
		$this->changeStatus();

		return $this->redirect(['index']);
	}

	/**
	 * The change of status of visitors
	 *
	 * @throws \Throwable
	 */
	protected function changeStatus()
	{
		$visitors = $this->getVisitors();

		foreach ($visitors as $visitor) {
			$genres = [];
			foreach ($visitor->genres as $genre) {
				$genres[] = $genre->name;
			}

			$visitor->status_id = (in_array($this->getCurrentMusic(), $genres)) ? 2 : 1;
			$visitor->update(true, ['status_id']);
		}
	}

	/**
	 * Gets all visitors
	 *
	 * @return Visitors visitors
	 * @throws NotFoundHttpException
	 */
	protected function getVisitors()
	{
		if (($visitors = Visitors::find()->all()) !== null) {
			return $visitors;
		}

		throw new NotFoundHttpException('The visitors does not exist.');
	}

	/**
	 * Gets current music
	 *
	 * @return mixed
	 * @throws NotFoundHttpException
	 */
	protected function getCurrentMusic()
	{
		$genresHistory = $this->getLastMusic();
		return $genresHistory->genre->name;
	}

	/**
	 * Gets last music
	 *
	 * @return last music
	 * @throws NotFoundHttpException
	 */
	protected function getLastMusic()
	{
		if (($lastMusic = GenresHistory::find()->orderBy(['genres_history_id' => SORT_DESC])->one()) !== null) {
			return $lastMusic;
		}

		throw new NotFoundHttpException('The requested music does not exist.');
	}

	/**
	 * Checking exist visitors in bar
	 *
	 * @return bool
	 */
	protected function checkExistVisitors()
	{
		if (!empty(Visitors::find()->asArray()->all())) {
			return true;
		}

		return false;
	}


}

frontend/controllers/VisitorController.php
<?php

namespace frontend\controllers;

use yii\web\Controller;
use yii\web\NotFoundHttpException;

use common\models\Genres;
use common\models\Visitors;
use common\models\Statuses;

/**
 * Visitor controller
 */
class VisitorController extends Controller
{

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	/**
	 * Deletes an existing Visitors model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 * @throws \Throwable
	 * @throws \yii\db\StaleObjectException
	 */
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();

		return $this->redirect(['site/index']);
	}

	/**
	 * View visitor
	 *
	 * @param $id
	 *
	 * @return string
	 */
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => Visitors::findOne($id),
		]);
	}

	/**
	 * Creates a new random Visitors model.
	 *
	 * @return mixed
	 * @throws NotFoundHttpException
	 */

	public function actionCreate()
	{
		$visitor = new Visitors();

		$names = ['Игорь', 'Костя', 'Евгений', 'Федор', 'Олег'];
		$randName = $names[rand(0, count($names)-1)];
		$visitor->name = $randName;

		$statuses = $this->getStatuses();
		$randStatus = $statuses[array_rand($statuses)]['status_id'];
		$visitor->status_id = $randStatus;

		$allGenres = $this->getGenres();
		$randGenres = $this->getRandomGenres($allGenres);
		$visitor->genre_id = $randGenres;

		$visitor->save();

		return $this->redirect(['site/index']);
	}

	/**
	 * Delete random visitor model
	 *
	 * @throws \Throwable
	 * @throws \yii\db\StaleObjectException
	 */
	public
	function actionRandDelete()
	{
		$visitors = $this->getVisitors();

		$this->actionDelete($visitors[array_rand($visitors)]['visitor_id']);
	}

	/**
	 * Finds the Visitors model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id
	 *
	 * @return Visitors the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Visitors::findOne($id)) !== null) {
			return $model;
		}

		throw new NotFoundHttpException('The requested visitor does not exist.');
	}

	/**
	 * Finds the Visitors model
	 *
	 * @return Visitors the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function getVisitors()
	{
		if (!empty(($visitors = Visitors::find()->asArray()->all()))) {
			return $visitors;
		}

		throw new NotFoundHttpException('Visitors is not exist');
	}

	/**
	 * Finds the Genres model
	 *
	 * @return Genres the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function getGenres()
	{
		if (!empty(($genres = Genres::find()->asArray()->all()))) {
			return $genres;
		}

		throw new NotFoundHttpException('Genres is not exist');
	}

	/**
	 * Gets random count random genres
	 *
	 * @param array $genres
	 *
	 * @return array random genres
	 */
	protected function getRandomGenres($genres)
	{
		$randGenresCount = rand(1, count($genres));
		$randGenres = (array)array_rand($genres, $randGenresCount);

		$result = [];
		for ($i = 0; $i < count($randGenres); $i++) {
			array_push($result, $genres[$randGenres[$i]]['genre_id']);
		}

		return $result;
	}

	/**
	 * Finds the Statuses model
	 *
	 * @return Statuses the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function getStatuses()
	{
		if (!empty(($statuses = Statuses::find()->asArray()->all()))) {
			return $statuses;
		}

		throw new NotFoundHttpException('Statuses is not exist');
	}


}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

use yii\grid\GridView;

use yii\helpers\Html;
use yii\helpers\ArrayHelper;

use common\models\Section;
use common\models\Statuses;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model common\models\Visitors */

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Сейчас играет <?= $currentMusic ?>!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><?= Html::a('Сменить трек', ['change-music'], ['class' => 'btn btn-lg btn-success']) ?></p>
        <!--        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>-->
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-xs-12">
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],

                        'name',
                        [
                            'attribute' => 'status_id',
                            'value' => function ($data) {
                                return $data->status->status;
                            },
                            'filter' => ArrayHelper::map(
                                Statuses::find()->where(['is not', 'status_id', null])->asArray()->all(),
                                'status_id',
                                'status'
                            ),
                        ],

                        [
                            'attribute' => 'genres_id',
                            'value' => function ($data) {
                                $html = "";
                                foreach ($data->genres as $gr) {
                                    $html .= "{$gr->name} ";
                                }
                                return $html;
                            },
                        ],


                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{view} {delete}',
                            'buttons' => [
                                'delete' => function ($myUrl, $model, $key) {
                                    return Html::a('', ['/visitor/delete/' . $model->visitor_id], ['class' => 'glyphicon glyphicon-trash']);
                                },
                                'view' => function ($myUrl, $model, $key) {
                                    return Html::a('', ['/visitor/view/' . $model->visitor_id], ['class' => 'glyphicon glyphicon-eye-open']);
                                },
                            ],


                        ],
                    ],
                ]); ?>
            </div>
            <p style="text-align: right;">
                <?= Html::a('Кто то пришел', ['visitor/create'], ['class' => 'btn btn-lg btn-success']) ?>
                <?=($exitsVisitors) ? Html::a('Кто то ушел', ['visitor/rand-delete'], ['class' => 'btn btn-lg btn-danger']):''?>
                <?= Html::a('Проверить бар', ['check-bar-status'], ['class' => 'btn btn-lg btn-warning']) ?>
            </p>
        </div>

    </div>
</div>